config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'
  resources :foodies

  resources :restaurants do
    resources :reviews
    resources :reservations
  end
  
    resources :sessions, only: [:new, :create, :destroy]
end

app/models/foodie.rb
class Foodie < ActiveRecord::Base
	has_secure_password
	has_many :reservations
	has_many :reviews
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	validates :name, :user_phone, :email_address, :size_of_party, presence: true
	validates :user_phone, :size_of_party, numericality: {only_integer: true}
	belongs_to :restaurant
	belongs_to :foodie
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_secure_password

	has_many :reviews
	has_many :reservations

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
  	@current_user ||= Foodie.find(session[:foodie_id]) if session[:foodie_id]
  end

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end

  helper_method :current_user

end

app/controllers/foodies_controller.rb
class FoodiesController < ApplicationController
  def index
  	@foodies = Foodie.all
  end

  def show
  	@foodies = Foodie.find(params[:id])
  end

  def new
  	@foodie = Foodie.new
  end

  def create
  	@foodie = Foodie.new(foodie_params)
  	if @foodie.save
  		redirect_to foodies_path, notice: "You are now a foodie!"
  	else
  		render "new"
  	end
  end

  def edit
  	@foodie = Foodie.find(params[:id])
  end

  def update
    @foodie = Foodie.find(params[:id])
    if @foodie.update_attributes(foodie_params)
      redirect_to foody_path(@foodie)
    else
      render :edit
    end
  end

  def upload
    uploaded_io = params[:current_user][:picture]
    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
    end
  end

  private
  def foodie_params
  	params.require(:foodie).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant
  def index 
  	@reservations = Reservation.all
    @restaurants = Restaurant.all
  end

  def show

  	@reservation = Reservation.find(params[:id])
  end

  def new 		#user to create a reservation using the form
  	@reservation = Reservation.new
    @restaurants = Restaurant.all
  end

  def edit 		#make changes to the reservation
  	@reservation = Reservation.find(params[:id])
  end

  def create 	#add the new reservation database
  	@reservation = @restaurant.reservations.build(reservation_params)
   @restaurants = Restaurant.all
  	if @reservation.save
  		redirect_to restaurant_reservation_path(@restaurant,@reservation) ## go to the confirmation page
  	else
  		render :new
  	end
  end
  

  def update 	#saving the reservation
  	@reservation = Reservation.find(params[:id])
  	if @reservation.update_attributes(reservation_params)
  		redirect_to restaurant_reservation_path(@restaurant,@reservation)
  	else
  		render :edit
  	end
  end

  def destroy	#deleting the reservation
  	@reservation = Reservation.find(params[:id])
  	@reservation.destroy
  	redirect_to restaurants_path(@restaurants)
  end

  private
  def reservation_params
  	params.require(:reservation).permit(:name, :user_phone, :email_address, :size_of_party, :comments_and_requests,:comments,:restaurant_id, :res_time)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
    @restaurants = Restaurant.all

  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
    @reservations = Reservation.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant[:phone_number] = restaurant_params[:phone_number].gsub(/[^0-9a-z ]/i, '')
    
    @restaurant.save
    if @restaurant.save
      redirect_to restaurants_url
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to products_path
  end

  private
  def restaurant_params
  	params.require(:restaurant).permit(:name, :password, :password_confirmation, :address, :capacity, :bio, :phone_number,:comments)
  end
 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :load_restaurant
	# before_filter :ensure_logged_in, only: [:create, :destroy]

	def index 
		@reviews = Review.all
	end

	def show
		@review = Review.find(params[:id])

	end

	def create
		@review = @restaurant.reviews.build(review_params) 
		# We have to use @restaurant in order to connect review and specific restaurant.
		# @review.user = current_user
		if @review.save
			redirect_to restaurant_path(@restaurant),flash[:notice] = "Review created successfully!"
		else
			redirect_to restaurants_path
		end
	end

	def destroy
		@review = @restaurant.reviews.find(params[:id])
		# @review = Review.find(params[:id]
		@review.destroy
		redirect_to restaurant_path(@restaurant) 
	end

	def edit 
		@review = Review.find(params[:id])
	end

	def update
			@review = @restaurant.reviews.find(params[:id])
			if @review.update_attributes(review_params)
				redirect_to restaurant_path(@restaurant) 
			# To defin the specific product 
		else
			render :edit
		end
	end
end

private
def review_params
	params.require(:review).permit(:comments, :title,:rating,:foodie_id)
end

def load_restaurant
	@restaurant = Restaurant.find(params[:restaurant_id])
end

# We use load_restaurant in order to find specific restaurant.

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    debugger

  	foodie = Foodie.find_by(email: params[:email])
  	if foodie && foodie.authenticate(params[:password])
  		session[:foodie_id] = foodie.id
  		redirect_to foody_path(foodie), notice: "Logged in!" #how to get the path to show a single url
  	else 
  		render "new"
  	end
  end

  def destroy
  	session[:foodie_id] = nil
  	redirect_to foodies_path notice: "Logged out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodies_helper.rb
module FoodiesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/time_helper.rb
module TimeHelper
	def time_to_next_half_hour(time) 
	    array = time.to_a
	    half = ((array[1] % 60) / 30.0).ceil
	    array[1] = (half * 30) % 60
	    Time.local(*array) + (half == 4 ? 3600 : 0)
	end

	
end

app/views/foodies/_form.html.erb
<%= form_for(@foodie) do |f| %> 
<% if @foodie.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
			<ul>
				<% for message in @foodie.errors.full_messages %>
				<li><% message %></li>
				<% end %>
			</ul>
	</div>
<% end %>

<div class="field">
	<%= f.label :name %><br/>
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :email %><br/>
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :password %><br/>
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
</div>

<div class="actions"><%= f.submit %></div>
<% end %>

app/views/foodies/_profileform.html.erb
<%= form_for(@current_user) do |f| %> 
<% if @current_user.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
			<ul>
				<% for message in @current_user.errors.full_messages %>
				<li><% message %></li>
				<% end %>
			</ul>
	</div>
<% end %>

<div class="field">
	<%= f.label :bio %><br/>
	<%= f.text_area :bio %>
</div>

<div class="field">
	<%= f.label "Profile Picture" %><br/>
	<%= f.file_field :picture %>
</div>


<% end %>

app/views/foodies/edit.html.erb
<h1>Foodies#edit</h1>
<p>Find me in app/views/foodies/edit.html.erb</p>

<%= render 'profileform'  %>
<%= render 'form'  %>

app/views/foodies/index.html.erb
<div class="title-page">

  <div class="center-block">
<h1>Welcome to FoodieTable</h1>

app/views/foodies/new.html.erb
<h1>Become a Foodie!</h1>
<p>Find me in app/views/foodies/new.html.erb</p>

<%= render 'form'  %>

app/views/foodies/show.html.erb
<h1>Foodies#show</h1>
<p>This is your profile - Find me in app/views/foodies/show.html.erb</p>
<br/>

<h2 class="userinfo">
      <% if current_user %>
        Welcome <%= current_user.name %>!
        
      <% end %>
    </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodietable</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="js/jquery-1.9.1.min.js"></script>
<script src="js/transition.js"></script>
  <%= csrf_meta_tags %>
</head>
<div class="container">
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get g#ouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/#">FoodieTable</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="/restaurants/new">Add Restaurant</a></li>
          </ul>
        </li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              Signed in as <%= current_user.name %>
                <span class="caret"></span>
                <ul class="dropdown-menu" role="menu">
                 <li>  <%= link_to "View Profile", foody_path(current_user) %></li>
                 <li>   <%= link_to "Edit Profile", edit_foody_path(current_user) %></li>
                
                    </a></ul>
           
           
            <li> <%= link_to "Log out", session_path("current"), :method => :delete %><li></ul>
        <% else %><li> <%= link_to "Log in", new_session_path %></li>
        <li><%= link_to "Sign Up", new_foody_path %></li><% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%= yield %>


   
</div></div>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_for([@restaurant,@reservation]) do |f| %>
<!-- we need diner name, diner phone number, dinner email address, comments and request box, submit button -->
<% if @reservation.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this product from being saved:</h2>

      	<ul>
      		<% @reservation.errors.full_messages.each do |msg| %>
        	<li><%= msg %></li>
      		<% end %>
      	</ul>
    </div>
<% end %>

	<div class="field">
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :user_phone %><br/>
		<%= f.number_field :user_phone %>
	</div>
	<div class="field">
		<%= f.label :email_address %><br/>
		<%= f.text_field :email_address %>
	</div>
	<div class="field">
		<%= f.label :size_of_party %><br/>
		<%= f.number_field :size_of_party %>

	</div>
	<div class="field">
		<%= f.label :comments_and_requests %><br/>
		<%= f.text_area :comments_and_requests %>
	</div>
	<div class="actions">
		<%= f.submit %>
		<%= f.hidden_field :res_time, :value =>params[:res_time]%>
	</div>
<% end %>

app/views/reservations/_index_form.html.erb
<%= form_for(@reservation) do |f| %>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

<p>Make necessary changes to your reservation here</p>

<%= render 'form' %>

app/views/reservations/index.html.erb
<h1>Hello Foodie! Let's find the restaurant you would like to eat at!</h1>
<p>What do you feel like eating?</p>
<p>Categories here</p>
<p>Here's a list of restaurants under that category.  Choose one</p>
<p>List of restaurants here</p>
<p>What time yo?</p>
<p>Available times here</p>

app/views/reservations/new.html.erb
<h1>Let's Make Your Reservation at the <%= @restaurant.name %> for <%= params[:res_time].to_datetime.strftime("%H:%M") %></h1>

<%= render 'form' %> 

app/views/reservations/show.html.erb
<h1>Your Reservation has been made at <%= @restaurant.name %> for <%= @reservation.res_time.strftime("%H:%M") %></h1>
<p>Here's your reservation!</p>
<p>RESERVATION CONFIRMED. YAY!</p>

<p>Reservation is under <%= @reservation.name %></p>
<p>Party size is <%= @reservation.size_of_party%></p>
<p>Bon Appetit!</p>

<p><%= link_to "Edit", edit_restaurant_reservation_path(@restaurant,@reservation) %> <%= link_to "Make another reservation", new_restaurant_reservation_path(@restaurant,@reservation) %>


<%= link_to "Cancel your reservation.", restaurant_reservation_path(@restaurant,@reservation), method: :delete, data:{confirm: "Are you sure you want to cancel this reservation?"}  %></p>

<!-- the reason why we have to use instance variable is to call variable from another file.
 -->

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
	<% if @restaurant.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @restaurant.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :name %><br/>
    	<%= f.text_field :name %>
  	</div>
  	<div class="field">
  	  <%= f.label :password %><br/>
  	  <%= f.password_field :password %>
  	</div>
  	<div class="field">
  	  <%= f.label :password_confirmation %><br/>
  	  <%= f.password_field :password_confirmation %>
  	</div>
  	<div class="field">
		<%= f.label :address %><br/>
    	<%= f.text_field :address %>
  	</div>
  	<div class="field">
		<%= f.label :capacity %><br/>
    	<%= f.text_field :capacity %>
  	</div>
  	<div class="field">
		<%= f.label :bio %><br/>
    	<%= f.text_field :bio %>
  	</div>
  	<div class="field">
		<%= f.label :phone_number %><br/>
    	<%= f.telephone_field :phone_number %>
  	</div>
  	<div class="actions"><%= f.submit %></div>
<% end %>

app/views/restaurants/_reserve.html.erb
<% time_start = Time.now %></br>
<% time_end = Time.now.change({ hour: 22, min: 0, sec: 0 }) %>
<% time_now = time_to_next_half_hour(Time.now) %>

<h2>Make a Reservation</h2>

<% while time_now < time_end %>
	<% time_now += 30*60 %>
	<li>
		<% space_available=@restaurant.capacity %>
		<%= texttime = time_now.strftime("%H:%M") %>
		Space Available: 
		<% @reservations = @restaurant.reservations %>
		<% @reservations.each do |reservation| %>
			<% if reservation.res_time != nil && reservation.res_time <= time_now.strftime('%a, %d %b %Y %H:%M:%S') && reservation.res_time >= (time_now -(10*60*6)).strftime('%a, %d %b %Y %H:%M:%S') %>
				<% space_available -= reservation.size_of_party %>
			<% end %>
		<% end %>
		<%= space_available %>
		<% if space_available > 0 %>
				<%= link_to "Reserve", new_restaurant_reservation_path(@restaurant,@reservation,:res_time => texttime) %>
		<% end %>
		
	</a>
	</li>
<% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<div class="center-block">
<h2>List of Restaurants</h2>
<% @restaurants.each do |restaurant| %>
	<p><b><a href='/restaurants/<%= restaurant.id %>'><%= restaurant.name %></b></a></br>
		<%= restaurant.address %></br>
		<%= restaurant.bio %></br>
		<%= number_to_phone(restaurant.phone_number,area_code: true) %></br>
		</p>
<% end %>

</div>

app/views/restaurants/new.html.erb
<div class="center-block">
<h1>New Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="center-block">
<h1><%= @restaurant.name %></h1>
<b>Bio:</b> <%= @restaurant.bio %></br>
<b>Address:</b> <%= @restaurant.address %></br>
<b>Capacity:</b> <%= @restaurant.capacity %></br>
<b>Phone Number:</b> <%= number_to_phone(@restaurant.phone_number,area_code: true) %></br><br>

<p></p>
 

<p>Reviews for <%= @restaurant.name %></p>

<% @restaurant.reviews.each do |review| %>
<p>TITLE:</p><p><%= review.title %></p>
<p>COMMENTS:</p><p><%= review.comments %></p>
<p>RATING:</p><p><%= review.rating %></p>

	<%= link_to "Delete", restaurant_review_path(@restaurant,review), method: :delete, data:{confirm: "Are you sure you want to delete this comment?"}  %>

	<%= link_to "Edit", edit_restaurant_review_path(@restaurant,review) %>

<% end %>

<% if flash[:notice] %>
	<p class=notice>
	<%= flash[:notice] %>
	</p>
<% end %>



<%= form_for([@restaurant,@review]) do |f| %>


<div class="field"> 
	<%= f.label :title %><br/>
	<%= f.text_area :title %>
</div>

<div class="field"> 
	<%= f.label :comments %><br/>
	<%= f.text_area :comments %>
</div>

<div class="field"> 
	<%= f.label :rating %><br/>
	<%= f.text_area :rating %>
</div>



<div class="actions">
	<%= f.submit %> 
</div>

<%= link_to "All restaurants" ,restaurants_path(@restaurants) %>

<% end %>


<%= render 'reserve' %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>


<%= link_to "Create review" new_restaurant_review_path %>

app/views/reviews/destroy.html.erb
<h1>Your comment was deleted!</h1>
<%= link_to "All products", foody_path %>	

app/views/reviews/edit.html.erb
<h1>Edit your review</h1>	
<p>Enter the information to edit the Product<p>


<%= form_for([@restaurant, @review]) do |f| %> 

	<div class="field">
		<%= f.label :comments %><br/>
		<%= f.text_area :comments %>	
	</div>

	<div class="field">
		<%= f.label :title %><br/>
		<%= f.text_area :title %>	
	</div>

<div class="field">
		<%= f.label :rating %><br/>
		<%= f.text_area :rating %>	
	</div>


	<div class="actions">
		<%= f.submit %>
	</div>


	<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>